version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Run cibuild.sh
          command: bin/cibuild.sh
  test:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: Test
          command: bin/citest.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
